version: '3.2'

services:
  pc-autobackup:
    container_name: pc-autobackup
    volumes:
       - '~/PCAutoBackup:/root/PCAutoBackup'
       - '~/.pc_autobackup.cfg:/root/.pc_autobackup.cfg'
    network_mode: dlna_macvlan
    ports:
      - '1900:1900/udp'
    restart: unless-stopped
    build:
     context: ./

